fix "#1577" in regress_http.c
/home/runner/work/libevent/libevent/test/regress_http.c:4849:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 4849 |  char header_index[NI_MAXSERV];
      |  ^~~~
fix
/home/runner/work/libevent/libevent/test/regress_http.c:4850:20: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘const long unsigned int’} [-Werror=sign-compare]
 4850 |  for (int i = 0; i < size; ++i) {
      |